name: Java Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Build app
        run: mvn clean package

      - name: Run tests
        run: mvn test


